### ISSUE TITLE
[BUG] Kleidung (Körper)

### ISSUE THREAD

**Issue by CMoxify** [German-Classic-Company/gcrp_issues#14]
### Beschreibe dein Problem!

Nachdem man reconnected oder im Friseur war wird der Körper wieder resettet, sodass die haut wieder durch die Kleidung schaut. Außerdem Kann ich plötzlich auch den Körper nicht mehr ändern im Kleidershop. 

### Reproduktionsschritte

Reconnecten

### Erwartetes Verhalten

Der Körper sollte so bleiben wie man ihm im Kleiderladen ausgewählt hat.

### Betriebsystem

Windows 10

### Dein Character-Name

Ludwig von Moxburg

**Comment by DavidCoopsen** [comment]
Tryfix pending

**Comment by DavidCoopsen** [comment]
Tryfix pending

**Comment by DavidCoopsen** [comment]
fixed mit nächstem Restart
