### ISSUE TITLE
Funk wird getriggert, wenn man im Kleidungsmenü runtergeht mit den Pfeiltasten

### ISSUE THREAD

**Issue by Barisabi76** [German-Classic-Company/gcrp_issues#17]
### Beschreibe dein Problem!

Funk wird getriggert, wenn man im Kleidungsmenü runtergeht mit den Pfeiltasten

### Reproduktionsschritte

In einen Funk gehen, #-Menü öffnen und Pfeiltasterunter machen

### Erwartetes Verhalten

Fix

### Betriebsystem

W10

### Dein Character-Name

Baris Tunc

**Comment by fiftyy** [comment]
Fixed with next Restart.
