### ISSUE TITLE
Inventar Item verschwindet nach benutzen auch wenn Anzahl > 1 ist

### ISSUE THREAD

**Issue by Kuhva** [German-Classic-Company/gcrp_issues#18]
### Beschreibe dein Problem!

Inventar Item verschwindet nach benutzen auch wenn Anzahl > 1 ist

### Reproduktionsschritte

Item welches mehr als 1 mal vorhanden ist nutzen
Item Verschwindet aus inventar
Inventar neu öffnen korrekte Item anzahl wieder da

### Erwartetes Verhalten

kein inventar neu öffnen

### Betriebsystem

Windows 10

### Dein Character-Name

Jan Kuhva

**Comment by Foakx** [comment]
Fehler ist schon bekannt und schon mit TODO Comment versetzt
Siehe RemoveItem function => make async task, not async void and await it
