### ISSUE TITLE
Ts3

### ISSUE THREAD

**Issue by Kralle644** [German-Classic-Company/gcrp_issues#23]
### Beschreibe dein Problem!

Immer wenn ich 2 mal zum Beispiel P drücke werd ich aus welchen Grund auch immer auf dem Voice gemoved. Ebenfalls kann ich nicht mehr X menu und so weiter benutzen, und muss immer neu starten.

### Reproduktionsschritte

/

### Erwartetes Verhalten

naja NICHTS :D

### Betriebsystem

Windows 11

### Dein Character-Name

Jonas Kralle

**Comment by fiftyy** [comment]
Hey, @Kralle644 - Ich kann deinen Fehler leider nicht reproduzieren. Siehe folgendes Video:
https://streamable.com/u1w2lg
