### ISSUE TITLE
Pizza Job unendliche abgabe

### ISSUE THREAD

**Issue by OrcanArtz** [German-Classic-Company/gcrp_issues#24]
### Beschreibe dein Problem!

Man kann unendlich Pizzen abgeben bei Department of Justice und so in wenigen Sekunden alle Pizzen abgeben.

### Reproduktionsschritte

Starte den Pizza Job, fahr zu Department of Justice und spam einfach "E"

### Erwartetes Verhalten

Nach einmal abgeben sollte man dort erst mal nichts mehr abgeben können.

### Betriebsystem

Windows 11

### Dein Character-Name

Chris Daun

**Comment by DavidCoopsen** [comment]
pending fix

**Comment by Nxooah** [comment]
Sollte mit dem nächsten Server-Restart behoben sein. Falls nicht bitte dieses Issue neuöffnen.
