### ISSUE TITLE
Ausweisbug

### ISSUE THREAD

**Issue by Nico1712** [German-Classic-Company/gcrp_issues#25]
### Beschreibe dein Problem!

Wenn ich einen Ausweis übergeben möchte kommt dieser nicht bei der Person gegenüber an.

### Reproduktionsschritte

Ausweis geben.

### Erwartetes Verhalten

Ausweis sollte angezeigt werden.

### Betriebsystem

Windows 10

### Dein Character-Name

Luis Kawasaki

**Comment by Kuhva** [comment]
Wolltest du deinen Ausweis in der Einreise zeigen? Falls nicht legale oder illegale Whitelist?

**Comment by Nico1712** [comment]
Nein, allgemein.
Ich bin Rang 12er in der Fahrschule, man sieht diesen auch nicht außer Dienst.
Kegale Einreise
