### ISSUE TITLE
Hüte können nicht ausgezogen werden.

### ISSUE THREAD

**Issue by Dxve948** [German-Classic-Company/gcrp_issues#26]
### Beschreibe dein Problem!

Ich könnte bei LSC Kleiderschrank nicht "Kein Hut" auswählen. Alle anderen Hüte funktionieren.

### Reproduktionsschritte

Hut Versuchen im Kleiderschrank aus zu ziehen.

### Erwartetes Verhalten

Hut wird ausgezogen

### Zusatz

https://youtu.be/DV3YYXRvbNU

### Betriebsystem

Win 11

### Dein Character-Name

Dave Melon

**Comment by fiftyy** [comment]
**Fixed** mit nächstfolgenden Server-Restart.
