### ISSUE TITLE
Kennzeichen Farbe ändert sich.

### ISSUE THREAD

**Issue by Dxve948** [German-Classic-Company/gcrp_issues#27]
### Beschreibe dein Problem!

Habe mein Auto gestern mit einem Schwarzen Gelben Kennzeichen angemeldet und eingeparkt. Heute habe ich es ausgeparkt und es hat ein Weißes Keinzeichen.

### Reproduktionsschritte

Weiß ich nicht vielleicht durchs ein ausparken. Hab kein Geld es immer neu anzumelden.

### Erwartetes Verhalten

Kennzeichen sollte gleiche Farbe behalten

### Zusatz

![GTA5_2022 02 13-13 15](https://user-images.githubusercontent.com/66784336/153752677-a7cb2223-4ad2-47dc-ba4b-9136b803ace5.png)

### Betriebsystem

Win 11

### Dein Character-Name

Dave Melon

**Comment by fiftyy** [comment]
Fixed@Next Update - Bitte melde dich im Support mit @fiftyy für eine Erstattung deiner Kennzeichen-Farbe.
