### ISSUE TITLE
Geld weg Bug

### ISSUE THREAD

**Issue by AmneeeZia** [German-Classic-Company/gcrp_issues#28]
### Beschreibe dein Problem!

Geld abgehoben und es ist verschwunden

### Reproduktionsschritte

Ich habe soeben (ca. 14:10 Uhr) am Würfelpark an der Fleeca Bank am Bankautomat Geld abgehoben und auf ''Alles abheben'' geklickt waren 6792$ das Geld hatte ich danach aber nicht auf der Hand und auf dem Konto war auch nichts mehr.

### Erwartetes Verhalten

Das ich mein Geld auf der Hand hab ??

### Betriebsystem

Windows 10

### Dein Character-Name

Kiano Montoya

**Comment by fiftyy** [comment]
Kann ich leider nicht reproduzieren. Falls dieser Fehler nochmal auftreten sollte erstelle bitte ein neues Issue mit einem Video.
