### ISSUE TITLE
Graspflanzen verschwinden

### ISSUE THREAD

**Issue by DimitriXier47** [German-Classic-Company/gcrp_issues#29]
### Beschreibe dein Problem!

Sobald man sich von seiner Graspflanze wegbewegt bzw paar Hundermeter weiter despawnt diese.

### Reproduktionsschritte

Wenn man die Pflanze platziert und dann eine runde um block fährt verschwindet diese

### Erwartetes Verhalten

Die Pflanze sollte dort stehen bleiben dass man nach einer bestimmten Zeit wiederkommen kann um die zu Ernten

### Betriebsystem

Windows 10

### Dein Character-Name

Shane Montoya

**Comment by fiftyy** [comment]
Kann das leider nicht reproduzieren. Siehe folgendes Video:
https://streamable.com/mbjrpk

**Comment by DimitriXier47** [comment]
Und du musst so weit aus der Reichweite dass dieser nicht gerendert wird und das vielleicht auch für paar minuten

**Comment by fiftyy** [comment]
Bin dran.

**Comment by fiftyy** [comment]
Sollte mit dem nächsten Server-Restart behoben sein. Falls nicht bitte dieses Issue neuöffnen.
