### ISSUE TITLE
Blöcke bei dem Handy Minispiel nicht mehr Zusehen

### ISSUE THREAD

**Issue by Taqqzz** [German-Classic-Company/gcrp_issues#3]
### Beschreibe dein Problem!

Nachdem Wallpaper Wechsel werden mir bei dem Handy Minispiel die Blöcke nicht mehr angezeigt sondern nur der Hintergrund.

### Reproduktionsschritte

1. Das Handy öffnen 
2. Minispiel Starten
3. Minispiel Schließen 
4. Einstellungen öffnen und Wallpaper ändern
5. Minispiel Starten

### Erwartetes Verhalten

Funktionierendes Minispiel auch nach dem das Wallpaper geändert wurde

### Zusatz

![image](https://user-images.githubusercontent.com/74612905/153663796-e63d344d-8bf9-495a-9786-fcbfbf2fccd8.png)

### Betriebsystem

Windows 10

### Dein Character-Name

Alvess Young

**Comment by fiftyy** [comment]
Fixed@v0.0.2 https://forum.gcrp.cc/forum/thread/18-v0-0-2-12-02-2022/
