### ISSUE TITLE
Kofferraum nicht einsehbar

### ISSUE THREAD

**Issue by Barisabi76** [German-Classic-Company/gcrp_issues#30]
### Beschreibe dein Problem!

Man kann den Kofferraum öffnen, jedoch ihn danach nicht einsehen. Nix reinlegen etc.

### Reproduktionsschritte

Auto kaufen, Kofferraum öffnen, versuchen einzusehen

### Erwartetes Verhalten

Fix

### Betriebsystem

W10

### Dein Character-Name

Baris Tunc

**Comment by fiftyy** [comment]
Bitte ein Video.
