### ISSUE TITLE
Keine Animation beim Handy

### ISSUE THREAD

**Issue by NiklasJan** [German-Classic-Company/gcrp_issues#31]
### Beschreibe dein Problem!

Sobald man sein Handy rausholt, gibt es weder eine Animation oder ähnliches.

### Reproduktionsschritte

Bild Hoch um das Handy rauszuholen 

### Erwartetes Verhalten

Eine Animation damit man sieht ob man am Handy ist.

### Betriebsystem

Windows 10

### Dein Character-Name

Niklas Shadow

**Comment by fiftyy** [comment]
Wird bald eingebaut. Aber kein "Bug" bzw. Fehler.
