### ISSUE TITLE
Finger zeigen

### ISSUE THREAD

**Issue by NiklasJan** [German-Classic-Company/gcrp_issues#32]
### Beschreibe dein Problem!

Sobald man versucht mit "Y" seinen Finger zu zeigen, passiert nichts.

### Reproduktionsschritte

Y drücken

### Erwartetes Verhalten

Dass man seinen Finger mit "Y" zeigen kann.

### Betriebsystem

Windows 10

### Dein Character-Name

Niklas Shadow

**Comment by fiftyy** [comment]
Wird demnächst eingebunden.
