### ISSUE TITLE
Werbungen werden nicht ganz Angezeigt.

### ISSUE THREAD

**Issue by Dxve948** [German-Classic-Company/gcrp_issues#33]
### Beschreibe dein Problem!

In der Werbungs App sind die Texte etwas verrutscht glaube ich.

### Reproduktionsschritte

Werbungs App öffnen/ Werbung schalten.

### Erwartetes Verhalten

ganzer Text wird angezeigt

### Zusatz

![GTA5_2022 02 13-18 25](https://user-images.githubusercontent.com/66784336/153766956-77f30bb9-5d66-423b-99aa-cc9a08e4b69e.png)

### Betriebsystem

Win 11

### Dein Character-Name

Dave Melon

**Comment by fiftyy** [comment]
Fixed@v0.0.4
