### ISSUE TITLE
[Bug] Keyinput während LSPD Comp offen

### ISSUE THREAD

**Issue by CowCatDE** [German-Classic-Company/gcrp_issues#34]
### Beschreibe dein Problem!

Während man das Aktensystem vom LSPD offen hat, ist der Keyinput nicht deaktiviert. Also bei dem eingeben eines Buchstabens wie "N" wird einmal durchgefunkt

### Reproduktionsschritte

Aktensystem öffnen und Text eingeben

### Erwartetes Verhalten

Keine Interaktion mit der Spielumgebung

### Betriebsystem

Windows 11

### Dein Character-Name

Prof. Dr. Ethan Levine

**Comment by fiftyy** [comment]
Kann ich nicht reproduzieren. Falls dieser Fehler nochmal auftreten soll, bitte ein Video aufnahmen & dieses Issue wieder öffnen.
