### ISSUE TITLE
Charaktererstellung Augenfarbe Text <> Charakter/Vorschau

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#35]
### Beschreibe dein Problem!

Die Augenfarbe sind um eine Option verschoben (Text ist für die nächste Option, nicht für die momentan ausgewählte)

### Reproduktionsschritte

Charakter erstellen

### Erwartetes Verhalten

Beschreibung 

### Zusatz

![download](https://user-images.githubusercontent.com/2738909/153773901-04e210f1-bb28-48e7-b7b4-836af6fb39b6.jpg)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by fiftyy** [comment]
Eigentlich ist das richtig so. Bzw. Tief-Schwarz ist eine Augenfarbe?

**Comment by ImperatorAD** [comment]
Stimmt bei allen Farben leider nicht, sind alle um einen Eintrag verschoben. Zusätzlich sind alle Augenfarben verfügbar (Inkl. tief schwarz, Schlangenaugen usw.), welches mehr oder weniger sinnlos ist.

**Comment by Kuhva** [comment]
Sollte im nächsten Update behoben sein
