### ISSUE TITLE
Fahrzeugmotor

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#37]
### Beschreibe dein Problem!

Wenn man ein Fahrzeug mit laufendem Motor verlässt, geht der Motor teilweise automatisch aus. Wenn man nun in das Fahrzeug einsteigt und den Motor starten will, wird einem der Status "Motor wurde ausgeschaltet" angezeigt und der Motor startet nicht. Man muss also 2x den Motor starten.

Dies fällt besonder auf bei Jobs, wo man of das Fahrzeug verlassen muss z.B. Pizzabote .

### Reproduktionsschritte

Fahrzeug mit laufenden Motor verlassen und wieder einsteigen.

### Erwartetes Verhalten

A: Der Motor bleibt an, wenn man ihn nicht ausschaltet
B: Der Motor startet, wenn man auf Motor starten drückt. 

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by Kuhva** [comment]
Nicht reproduzierbar

**Comment by ImperatorAD** [comment]
https://www.youtube.com/watch?v=mT-vGRvBhtY

**Comment by ImperatorAD** [comment]
@Kuhva Bei mir tritt das Problem regelmäßig auf und lässt sich einfach reproduzieren.
