### ISSUE TITLE
Handy Nachrichten - Verlauf

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#38]
### Beschreibe dein Problem!

Moin, Nachrichten werden nicht in der richtigen Reihenfolge angezeigt

### Reproduktionsschritte

Hand öffnen - Nachrichten. Siehe Screenshot

### Erwartetes Verhalten

Chronologische Reihenfolge

### Zusatz

![download](https://user-images.githubusercontent.com/2738909/154565810-aefe54fd-ef85-47b0-bb3c-35ad67a4899d.jpg)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by ImperatorAD** [comment]
Nachtrag: Nach Neubeitritt auf den Server werden die Nachrichten in der richtigen Reihenfolge angezeigt.

**Comment by ImperatorAD** [comment]
Nachtrag Nr. 2: Der Verlauf ist wieder falsch. Die 3. Nachrichten hängern unten fest und neue sind immer dadrüber.

**Comment by Kuhva** [comment]
Sollte mit dem nächsten Update behoben sein
