### ISSUE TITLE
X - Menü - Fehlende Animation (Fahrzeug)

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#40]
### Beschreibe dein Problem!

Beim Hovern über eine Option im X-Menü "wackelt" das ganze Menü und eine Animation wird angezeigt. Dies passiert nicht bei der Option: Fahrzeug abschließen

### Reproduktionsschritte

X-Menü im Fahrzeug öffnen

### Erwartetes Verhalten

Animationen für alle Unterpunkte

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/154579356-ad5c5af8-5cd7-4137-803d-2d0d866cc8e6.png)
![image](https://user-images.githubusercontent.com/2738909/154579362-71d2bd22-7a35-4518-9c05-4e27aa8c70d3.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by Foakx** [comment]
Hallo @ImperatorAD 
Nenne uns bitte deine Auflösung, welche du in deinem Spiel ausgewählt hast

**Trace - Development Team**

**Comment by ImperatorAD** [comment]
https://prnt.sc/26y1ybg

1920 x 1080

**Comment by Foakx** [comment]
Hast du die Möglichkeit, uns ein Video der Reproduktionsschritte zu schicken?

**Comment by ImperatorAD** [comment]
Ich gucke mal ob ich ShadowPlay zum laufen bekomme, das will gerade nicht. Ich gebe mein bestes :)

**Comment by ImperatorAD** [comment]
Das Menü schenint bei mir jetzt wieder richtig zu funktionieren. Sieht nach einem vereinzelten Fehler an dem Tag für mich aus.
