### ISSUE TITLE
Durch Animationen gespante Props verschwinden nicht

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#42]
### Beschreibe dein Problem!

Kaffeebecher oder Wasserflaschen (und evtl. auch andere - nicht getestet) verschwinden nicht am Ende der Animation

### Reproduktionsschritte

Flasche Wasser trinken, "Kaffee tringen" animation starten und wieder abbrechen (Entweder durch "Animation abbrechen" oder andere Aktionen wie in ein Fahrzeug einsteigen oder eine andere Animation starten

### Erwartetes Verhalten

Objekt verschwindet/wird auf den Boden fallen gelassen

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/154695994-36635309-f791-416b-a60b-1f7a2e99025f.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by DavidCoopsen** [comment]
Danke für deinen Bugreport! Der Fehler sollte mit dem nächsten Update behoben sein.
