### ISSUE TITLE
Bootshändler

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#43]
### Beschreibe dein Problem!

Boote sind etwas groß für die Garage :)

### Reproduktionsschritte

Bootshändler und "Marquis" oder "Tug"! auswählen

### Erwartetes Verhalten

Keine Autogarage?

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/154702354-9960966a-2b48-40d7-9f4c-b426cc2eb58b.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by fiftyy** [comment]
![hshop-fix](https://user-images.githubusercontent.com/20678496/155890400-f66140f2-d712-463d-a494-18f9693d2e32.PNG)
![bshop-fix](https://user-images.githubusercontent.com/20678496/155890404-24d35cb7-fcb6-4406-9b85-865194159a09.PNG)

Fixed@v0.1.1 - Next Restart.
