### ISSUE TITLE
Grapeseed Garage

### ISSUE THREAD

**Issue by CarnastrosLP** [German-Classic-Company/gcrp_issues#44]
### Beschreibe dein Problem!

ich habe mein Auto ausgeparkt dann wurde es wo anders geortet Schluss endlich war es in der verwahrstelle die letzten zweimal hat es bei der Garage mein Auto beim Bürgershot ausgeparkt

### Reproduktionsschritte

einparken und ausparken 

### Erwartetes Verhalten

das es bei der Garage ausgeparkt wird und nicht irgendwo 

### Betriebsystem

Windows 11

### Dein Character-Name

Leo Daun

**Comment by DavidCoopsen** [comment]
Wir konnten den Fehler leider nicht reproduzieren. Bitte probiere es erneut aus, und gebe uns Rückmeldung ob der Fehler behoben ist!

**Comment by Kuhva** [comment]
//Keine Rückmeldung mehr
