### ISSUE TITLE
Workstation - Hinweis zur Abholung

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#45]
### Beschreibe dein Problem!

Abholungshinweis erwartet eine Zeitreise -> Zeit bis zum 15.02.2022 29:59, aber es ist heute der 19.02.2022 14:00

### Reproduktionsschritte

Workstation laufen haben, aber an einer anderen einen Auftrag starten wollen.

### Erwartetes Verhalten

Richtigen Zeitpunkt anzeigen

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/154802237-85a36626-6bae-4acf-aa4a-2f7a7cafbc49.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by fiftyy** [comment]
Wichtig zu wissen ist, du darfst nur eine Workstation gleichzeitig am laufen haben.

**Comment by ImperatorAD** [comment]
Okay, kann ich das Zeig ewig in der Workstation bunkern oder verschwindet das irgendwann?

**Comment by fiftyy** [comment]
@DavidCoopsen

**Comment by DavidCoopsen** [comment]
Danke für deinen Bugreport @ImperatorAD!

Deine produzierten Items werden **NICHT** gelöscht. Es ist aber gewollt das du keine zweite Workstation nutzen kannst. Du erhälst die Nachricht aus folgendem Grund:

In der Anfangszeit war es möglich mehrere Workstations gleichzeitig zu befüllen, dies ist nun nicht mehr gewollt, weshalb wir es blockieren einen neuen Produktionsvorgang zu starten. Du erhälst zusätzlich beim öffnen der Workstation die Mitteilung, dass du noch Items in einer Workstation liegen hast. Das erklärt auch, weshalb du in der Schmelze keinen neuen Produktionsvorgang starten kannst. In deinem Fall befinden sich noch Items in der Seilerei. Solange die Items darin verbleiben, kannst du keinen erneuten Produktionsvorgang starten. Dieses Verhalten ist gewollt.

Solltest du noch weitere Fragen haben, melde dich gerne im TS bei mir oder per Discord!

**Comment by DavidCoopsen** [comment]
Danke für deinen Bugreport @ImperatorAD!

Deine produzierten Items werden NICHT gelöscht. Es ist aber gewollt das du keine zweite Workstation nutzen kannst. Du erhälst die Nachricht aus folgendem Grund:

In der Anfangszeit war es möglich mehrere Workstations gleichzeitig zu befüllen, dies ist nun nicht mehr gewollt, weshalb wir es blockieren einen neuen Produktionsvorgang zu starten. Du erhälst zusätzlich beim öffnen der Workstation die Mitteilung, dass du noch Items in einer Workstation liegen hast. Das erklärt auch, weshalb du in der Schmelze keinen neuen Produktionsvorgang starten kannst. In deinem Fall befinden sich noch Items in der Seilerei. Solange die Items darin verbleiben, kannst du keinen erneuten Produktionsvorgang starten. Dieses Verhalten ist gewollt.

Solltest du noch weitere Fragen haben, melde dich gerne im TS bei mir oder per Discord!

**Comment by DavidCoopsen** [comment]
Achso... Die Nachricht welche man beim öffnen erhält habe ich gerade abgeändert.
