### ISSUE TITLE
Eagle Pizza - Kartensymbol praktisch nicht sichtbar

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#46]
### Beschreibe dein Problem!

Symbol auf der Karte extrem klein und transparent.

### Reproduktionsschritte

karte öffnen

### Erwartetes Verhalten

Sichtbares Symbol

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/154805054-e9c1119b-e34e-419b-b368-2d2f23df5cdc.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by DavidCoopsen** [comment]
Danke für deinen Bugreport! Der Fehler sollte mit dem nächsten Restart behoben sein.
