### ISSUE TITLE
Auto Bugt weg

### ISSUE THREAD

**Issue by Pluto1235** [German-Classic-Company/gcrp_issues#47]
### Beschreibe dein Problem!

Immer wenn ich mein Auto aus der Grapeseed Garage ausgeparkt habe stand es nicht auf dem Parkplatz vor der Garage sondern vor dem Burger Shot Laden.

### Reproduktionsschritte

Auto in die Grapeseed Garage einparken, ausparken und über das Ortungsmenü auf dem Laptop findet man es bei Burger Shot wieder.

### Erwartetes Verhalten

Normalerweise sollte das Fahrzeug ja vor der Garage spawnen

### Betriebsystem

Windows 10

### Dein Character-Name

Luca Falucci

**Comment by DavidCoopsen** [comment]
Danke für deinen Bugreport! Der Fehler ist bereits bei uns eingegangen. Deswegen wird der Bugreport geschlossen
