### ISSUE TITLE
Animation beendet nicht wenn Fahrzeug betreten werden

### ISSUE THREAD

**Issue by DavidCoopsen** [German-Classic-Company/gcrp_issues#48]
### Beschreibe dein Problem!

Wenn man ein Fahrzeug betritt wird die laufende Animation nicht abgebrochen

### Reproduktionsschritte

Anim starten
In Auto steigen

### Erwartetes Verhalten

Animation abrechen

### Betriebsystem

Win 11

### Dein Character-Name

David Cooper

**Comment by Nxooah** [comment]
Gefixt
