### ISSUE TITLE
Fehlender Text / Unbekannt beim Kofferraum

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#49]
### Beschreibe dein Problem!

Titel beim Kofferraum ist nur "Unbekannt". 

### Reproduktionsschritte

Kofferraum vom "DLoader" öffnen

### Erwartetes Verhalten

Text wie "Kofferraum" oder "DLoader" oder "Bravado Duneloader"

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/154839181-50cf62ef-6f61-4b5d-becc-bc1c00e8752e.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by fiftyy** [comment]
Ist mit dem nächst-folgendem Update eingebaut ;) 

![676767900990](https://user-images.githubusercontent.com/20678496/154860347-8fc931c9-87e5-4aab-9e3d-278be3e4eeef.PNG)
