### ISSUE TITLE
Chihuahua Hotdogs

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#50]
### Beschreibe dein Problem!

Fehlermeldung [CODE-2] beim Kauf

### Reproduktionsschritte

Versuchen etwas zu kaufen

### Erwartetes Verhalten

Ausgewähltes Objekt wird gekauft

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/154857055-a65c06b7-c5d0-4c56-8b0b-fc668cedf0eb.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by DavidCoopsen** [comment]
Wenn ich das richtig sehe bist du da gerade im Burgershot. Der öffentliche Shop ist deaktiviert, wenn sich jemand von Burgershot im Dienst befindet. Deswegen bekommst du die Fehlermeldung

**Comment by Nxooah** [comment]
Guten Tag, der Hotdog laden hat ingame noch nicht eröffnet weswegen du dort nicht einkaufen kannst!

**Comment by ImperatorAD** [comment]
Hmmm okay hat mich nur gewundert, weil ich da gestern schon shoppen war :) Danke für die Antwort. (Eine passendere Fehlermeldung wäre super <3)
