### ISSUE TITLE
Heroes Cars - Fahrzeuge fehlerhaft geparkt

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#51]
### Beschreibe dein Problem!

Fahrzeuge parken nicht richtig

### Reproduktionsschritte

Vorbei fahren

### Erwartetes Verhalten

Fahrzeuge parken richtig

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/154969402-6ec2ea2e-7e81-4447-b420-0ab3ad969e0b.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by fiftyy** [comment]
Kann ich leider nicht reproduzieren. Kann eventuell daran liegen das die Fahrzeuge bei dir falsch gestreamed wurden.

Mit freundlichen Grüßen
f1fty
