### ISSUE TITLE
Workstation post 0.10 update - Alter Aufträge nicht sichtbar + Mengeneinstellung 

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#54]
### Beschreibe dein Problem!

Alte Aufträge kann ich nicht abholen (Siehe Screenshot)

Zusätzlich funktioniert die EIngabe der Anzahl nicht, es wird immer nur 1 Auftrag gestartet.

### Reproduktionsschritte

Sägewerk Workstation bedienen

### Erwartetes Verhalten

Beliebige Anzahl Aufträge sollten gestartet werden können.
Fertige Aufträge sollte man abholen können.

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/155857727-4feb5683-8a07-47a5-9904-6d4b86a1428d.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by ImperatorAD** [comment]
![image](https://user-images.githubusercontent.com/2738909/155872475-019cc055-2060-479d-8589-7321d0337887.png)
Sieht so aus als wäre jetzt alles weg? Oder es fehlt ein Button zum Abholen?

**Comment by fiftyy** [comment]
Solltest du dieses Problem immernoch haben so melde dich bitte im TS3-Support mit  @CowCatDE / @fiftyy .

Mit freundlichen Grüßen
f1fty
