### ISSUE TITLE
#Fahrzeugmenü - Kofferraum und Motorhaube schließen sich nicht

### ISSUE THREAD

**Issue by ImperatorAD** [German-Classic-Company/gcrp_issues#55]
### Beschreibe dein Problem!

Moin,

es ist nicht möglich den Kofferraum oder die Motorhaube über das # Menü wieder zu schließen.

### Reproduktionsschritte

# Fahrzeug -> Motorhaube / Kofferraum

### Erwartetes Verhalten

Beide Teile schließen wieder

### Zusatz

![image](https://user-images.githubusercontent.com/2738909/155893468-2b58f76a-9b97-48dc-ab42-4f382157ed2c.png)

### Betriebsystem

Windows 11

### Dein Character-Name

Gordon Price

**Comment by fiftyy** [comment]
Wie ist der Name des Fahrzeugs?

**Comment by ImperatorAD** [comment]
@fiftyy Ruiner

**Comment by fiftyy** [comment]
Kann ich leider nicht genau nachvollziehen warum dies genau so ist, deswegen muss ich dir leider sagen, dass ich das aktuell nicht beheben kann, falls mehrere Autos dieses Problem haben, so eröffne dieses Issue erneut. 

Mit freundlichen Grüßen
f1fty
