### ISSUE TITLE
Funkfrequzenen freischalten

### ISSUE THREAD

**Issue by RelOzX** [German-Classic-Company/gcrp_issues#56]
### Beschreibe dein Problem!

Funkfrequzen für wichtige Staatsorgane
zb. LSPD (500)

Aktuell können sich Polizeimitarbeiter in keine geschützen Funkfrequenzen einwählen. 

### Reproduktionsschritte

Als Polizeimitarbeiter oder Arbeitsloser
Handy öffnen -> FunkApp -> "500" eingeben -> auf das On/Off-Symbol klicken -> Pulsiert Gelb-Rot

### Erwartetes Verhalten

Als Polizeimitarbeiter sollte man sich in den Funk einwählen (Leuchtet Grün) und als _nicht_ Mitarbeiter eben nicht. (Pulsiert Gelb-Rot)

### Betriebsystem

Windows 11 Pro 22000.493

### Dein Character-Name

Chris Hooper

**Comment by fiftyy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Funk-Freqenzen für Fraktion Fix](https://trello.com/c/5MnZCtbD/55-funk-freqenzen-f%C3%BCr-fraktion-fix)

**Comment by fiftyy** [comment]
Fixed@Next Restart.
