### ISSUE TITLE
Busjob Bug

### ISSUE THREAD

**Issue by AmneeeZia** [German-Classic-Company/gcrp_issues#58]
### Beschreibe dein Problem!

Wenn man den Busjob ausübt und an den gegeben Haltestellen nicht bremst, kann man sich ausrollen lassen und gewinnt so vermutlich ein paar Sekunden. Denke der Bus sollte an der Haltestelle gefreezed werden, damit man nicht 10 meter vor der Haltestelle steht

### Reproduktionsschritte

Bus Job annehmen, volles Tempe an der Haltestelle vorbei

### Erwartetes Verhalten

Bus rollt weiter aus

### Betriebsystem

Windows 10

### Dein Character-Name

Kiano Montoya

**Comment by fiftyy** [comment]
Hey @AmneeeZia, danke für deinen Bug-Report.

Ich habe mir das Problem angeguckt & es behoben.
Bei dem nächsten Server-Restart bleibt der Bus nun direkt an der Haltestelle stehen.

https://streamable.com/xx4xc3

Mit freundlichen Grüßen
f1fty

**Comment by fiftyy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bus-Job - Der Bus rollt aus wenn man einer Halte-stelle anhält?](https://trello.com/c/UVhOgPR7/63-bus-job-der-bus-rollt-aus-wenn-man-einer-halte-stelle-anh%C3%A4lt)
