### ISSUE TITLE
Verbuggen

### ISSUE THREAD

**Issue by CMoxify** [German-Classic-Company/gcrp_issues#7]
### Beschreibe dein Problem!

Man verbugged nach ca. 5 min oder so auf dem Server und fliegt dann nur noch aus dem Voice raus. Wenn man f7 drückt bleibt man 10 Sekunden im Voice und fliegt sofort wieder raus. Außerdem kann man IC mit nichts mehr interagieren wenn das passiert. Ich kann nicht einmal arbeiten weil es ständig vorkommt.

### Reproduktionsschritte

Ich wüsste nicht wie

### Erwartetes Verhalten

Nicht und man sollte IC bleiben ohne ständig raus zu fliegen

### Betriebsystem

Windows 10

### Dein Character-Name

Ludwig von Moxburg

**Comment by CMoxify** [comment]
Bzw. passieret das wenn ich einfach durch die Stadt laufe oder fahre einfach das ich ausm Voice geworfen werde.

**Comment by fiftyy** [comment]
Andere Voice-Plugins sowie GVMP-Voice deaktivieren!

**Comment by fiftyy** [comment]
Andere Voice-Plugins sowie GVMP-Voice deaktivieren!
