### ISSUE TITLE
Kein Schaden mit Schlagstock

### ISSUE THREAD

**Issue by Barisabi76** [German-Classic-Company/gcrp_issues#8]
### Beschreibe dein Problem!

Kein Schaden mit Schlagstock

### Reproduktionsschritte

Schlagstockkaufen, schlagen

### Erwartetes Verhalten

Schaden hinzufügen

### Betriebsystem

W10

### Dein Character-Name

Baris Tunc

**Comment by Nxooah** [comment]
behoben
