### ISSUE TITLE
Leute disappearen im Burger MLO

### ISSUE THREAD

**Issue by Barisabi76** [German-Classic-Company/gcrp_issues#9]
### Beschreibe dein Problem!

Leute disappearen im Burger MLO

### Reproduktionsschritte

Mit mehreren Leuten in das MLO

### Erwartetes Verhalten

fix

### Zusatz

https://clips.twitch.tv/ProudUgliestNigiriRedCoat-Kub4BbpcJH33W5qF

### Betriebsystem

W10

### Dein Character-Name

Baris Tunc / James Montoya

**Comment by fiftyy** [comment]
Fixed with next Server-Restart@v.0.0.2
